// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/6/2025, 1:13:49 PM
const configMerger = require("/Users/alan/Documents/Web/locker/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/alan/Documents/Web/locker/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alan/Documents/Web/locker/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alan/Documents/Web/locker/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alan/Documents/Web/locker/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alan/Documents/Web/locker/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alan/Documents/Web/locker/plugins/**/*.{js,ts,mjs}","/Users/alan/Documents/Web/locker/composables/**/*.{js,ts,mjs}","/Users/alan/Documents/Web/locker/utils/**/*.{js,ts,mjs}","/Users/alan/Documents/Web/locker/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/alan/Documents/Web/locker/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/alan/Documents/Web/locker/app.config.{js,ts,mjs}"] } }));

module.exports = config
